### ISSUE TITLE
Please clarify that the graphql-config has precedence over options like ParserOptions.operations

### ISSUE THREAD

**Issue by therealgilles** [dimaMachina/graphql-eslint#1087]
### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox
> Please make sure the graphql-eslint version under `package.json` matches yours.
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**
The documentation does not make it clear that an option like `documents` in a graphql config is equivalent to ParserOptions.operations and takes precedence over it. Please kindly document equivalence and precedence behavior.

**Comment by B2o5T** [comment]
Thanks, would you want send a PR to this change? Also, in next major (v4) field `parserOptions.operations` will be renamed to `parserOptions.documents` to make consistency with graphql-config

**Comment by dimaMachina** [comment]
v4 were improved by removing `skipGraphQLConfig` option and introducing [programmatic usage](https://the-guild.dev/graphql/eslint/docs/usage/programmatic)
