### ISSUE TITLE
Feedback for new GraphQL-ESLint website

### ISSUE THREAD

**Issue by dimaMachina** [dimaMachina/graphql-eslint#1379]
Hi 👋! A new GraphQL-ESLint was just out with [playground page](https://the-guild.dev/graphql/eslint/play)!
All current documentation and a new one will be there!

Try it out https://the-guild.dev/graphql/eslint

Here you can share your feedback!

**Comment by connorjs** [comment]
My main request: Link to the rules in the side menu, or make it more noticeable somehow. It took me far too long to find the rules page (website, repo, website, repo, finally found it on website, about 10 min).

I like the clean new look, and I like the default to system preference for light/dark.

**Comment by B2o5T** [comment]
Thanks, I guess we need just setup in-site search

**Comment by gituserjava** [comment]
Currently playground supports only one file? Can it support multiple files which sometimes may be in sub directories.

**Comment by B2o5T** [comment]
@gituserjava sounds like a nice improvement, not sure if I will have time in the near future to work on it

if somebody wanna contribute you can check typescript-eslint website source code and make an attempt

also, I would like to migrate editor to the official monaco-editor package and allow specifying rule option if these exist

**Comment by FluorescentHallucinogen** [comment]
Where can I find the list of all rules with human descriptions, examples of correct and incorrect code, etc. like https://eslint.org/docs/latest/rules/?

Examples of correct and incorrect code could be taken from tests.

**Comment by connorjs** [comment]
<https://the-guild.dev/graphql/eslint/rules> - You can find it in the upper right of the website (see screenshot, Rules is selected).

<img width="955" alt="Screen shot showing Rules highlighted in the nav" src="https://github.com/dimaMachina/graphql-eslint/assets/22208536/5c1b13e5-61d2-4157-80ae-35627aa80f76">

_Note: I did not easily find this my first time either (my original comment)._

**Comment by dimaMachina** [comment]
rules link was moved to sidebar as well, closing
