### ISSUE TITLE
`naming-convention` rule `FieldDefinition.ignorePattern` config still checking underscores `_`

### ISSUE THREAD

**Issue by DanielEscorciaOrtiz** [dimaMachina/graphql-eslint#1719]
### Issue workflow progress

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox

     > For example, you can start off by editng the
     > ['basic' example on Stackblitz](https://stackblitz.com/github/B2o5T/graphql-eslint/tree/master/examples/basic).

     > Please make sure the graphql-eslint version under `package.json` matches yours.

- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

**To Reproduce**

With a schema like this:
```graphql
# src/schema.graphql

type SomeType {
  _someField_: Boolean!
}

type Query {
  someType: SomeType
}

type Mutation {
  mutType: SomeType
}
```

And a `.eslintrc` like this:
```js
module.exports = {
   [...]
    parserOptions: {
        schema: "src/schema.graphql"
    },
    rules: {
        '@graphql-eslint/naming-convention': [
            'error', {
                'FieldDefinition[parent.name.value=SomeType]': {
                    ignorePattern: ".*someField.*"
                }
            }
        ],
    }
}
```

I'm still receiving this errors:
```
<dir>/src/schema.graphql
  4:3  error  Leading underscores are not allowed   @graphql-eslint/naming-convention
  4:3  error  Trailing underscores are not allowed  @graphql-eslint/naming-convention
```

**Expected behavior**

It should ignore underscores if it matches the pattern, as described in the [docs](https://the-guild.dev/graphql/eslint/rules/naming-convention#ignorepattern-string)

**Environment:**

- OS: `macOs Ventura 13.4.1`
- `@graphql-eslint/eslint-plugin`: `3.19.1`
- Node.js: `v18.16.0`

**Additional context**

**Comment by B2o5T** [comment]
this is tricky to fix because `allowLeadingUnderscore` and `allowLeadingUnderscore` are global options that match `Name` nodes https://github.com/B2o5T/graphql-eslint/blob/819c046c2a459d2e601a7c58823b3fc4862ece0e/packages/plugin/src/rules/naming-convention.ts#L426-L435
