### ISSUE TITLE
Support for federation directives

### ISSUE THREAD

**Issue by gituserjava** [dimaMachina/graphql-eslint#1906]
We use federation directives like @key, @link, @inaccessible etc; how can configure the library to not to give errors on those directives? As of now we are getting below errors. Please advise.

`
0:0 error Parsing error: [graphql-eslint] Error while loading schema: Unknown directive "@link".
`
`Unknown directive "@key"`

**Comment by gituserjava** [comment]
#1063 did not work for me.

**Comment by dimaMachina** [comment]
fixed in 4.3.0, your federation subgraphs should be parsed without parsing errors now https://github.com/dimaMachina/graphql-eslint/issues/2812#issuecomment-2517103848
