### ISSUE TITLE
eslint dirctive hints are not working on version @graphql-eslint/eslint-plugin": "^3.20.1"

### ISSUE THREAD

**Issue by hrferdowsi** [dimaMachina/graphql-eslint#1962]
### Issue workflow progress

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox

     > For example, you can start off by editng the
     > ['basic' example on Stackblitz](https://stackblitz.com/github/B2o5T/graphql-eslint/tree/master/examples/basic).

     > Please make sure the graphql-eslint version under `package.json` matches yours.

- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

eslint directive hints are not working. This is not only doesn't work on my local but even in the graphql-eslint playground is not working neither. I tried all the eslint-disable-next-line or eslint-disable-line and other ones like # eslint-disable graphql/no-deprecated-fields and none of the works. 
you can test them on the playground too: 
[graphql-eslint official playground](https://the-guild.dev/graphql/eslint/play?s=scalar+DateTime%0A%0Atype+Post+%7B%0A++id%3A+ID%21%0A++title%3A+String%0A++aa%3A+SS+%23+eslint-disable-line%0A++createdAt%3A+DateTime%0A++modifiedAt%3A+DateTime%0A%7D%0A%0Atype+Query+%7B%0A++post%3A+Post%21%0A++posts%3A+%5BPost%21%5D%0A%7D%0A)

<img width="1449" alt="Screenshot 2023-10-25 at 2 15 53 pm" src="https://github.com/dimaMachina/graphql-eslint/assets/49377026/32d96f06-d292-416e-8f53-b62f6f74201b">

 To just give more details I am using the basic configuration in the eslintrc.cjs:
`module.exports = {
  env: {
    browser: true,
    node: true,
    es2021: true,
    es6: true,
    amd: true,
    jest: true,
  },
  root: true,
  parser: '@typescript-eslint/parser',
  plugins: ['@typescript-eslint'],

  extends: ['eslint:recommended', 'plugin:@typescript-eslint/recommended'],
  // rules always win over extends:
  rules: {
    '@typescript-eslint/no-explicit-any': 'off',
    '@typescript-eslint/ban-ts-comment': 'off',
    'no-unused-vars': 'off',
    '@typescript-eslint/no-unused-vars': 'off',
  },
  overrides: [
    {
      files: ['*.graphql'],
      parser: '@graphql-eslint/eslint-plugin',
      plugins: ['@graphql-eslint'],
      rules: {
        '@graphql-eslint/known-type-names': 'off',
        '@graphql-eslint/ban-ts-comment': 'off',
      },
      parserOptions: {
        schema: 'src/graphql/schemas/*.graphql',
      },
    },
  ],
};
`

**To Reproduce** Steps to reproduce the behavior:

try to use one of the eslint disable hints to ignore eslint check 
**Expected behavior**
The expected behavior  is eslint doesn't check the indicated disable code.

**Environment:**

- OS:
- `@graphql-eslint/eslint-plugin`:
- Node.js: 18

**Additional context**

**Comment by dimaMachina** [comment]
Eslint directives never worked when you have parsing errors, remove parsing errors and retry them

**Comment by dimaMachina** [comment]
just tried and it worked
<img width="366" alt="image" src="https://github.com/dimaMachina/graphql-eslint/assets/7361780/0210ebea-063b-4d25-951e-652ec4c0e35e">
