### ISSUE TITLE
Cannot read properties of undefined (reading 'parserServices')

### ISSUE THREAD

**Issue by waynezhang1995** [dimaMachina/graphql-eslint#1981]
### Issue workflow progress

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox

     > For example, you can start off by editng the
     > ['basic' example on Stackblitz](https://stackblitz.com/github/B2o5T/graphql-eslint/tree/master/examples/basic).

     > Please make sure the graphql-eslint version under `package.json` matches yours.

- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

We upgraded to `"@graphql-eslint/eslint-plugin": "4.0.0-alpha.0",` recently and this error started coming out.

We have the following setup in the `eslintrc.js` file
```
{
      files: '*.graphql',
      parser: "@graphql-eslint/eslint-plugin",
      parserOptions: {
        filePath: './graphql.config.js',
      },
    }
```

Based on the example, `parserOptions` seems unnecessary here and we do have a `graphql.config.js` file that colocates to the `eslintrc` file with the following content:
```javascript
module.exports = {
  schema: ['./schema.graphql'],
  documents: ['./src/**/*.{ts,tsx}'],
};

```

Any ideas please?

**To Reproduce** Steps to reproduce the behavior:

**Expected behavior**

**Environment:**

- OS: MacOS 14.1 
- `@graphql-eslint/eslint-plugin`:
- Node.js: v18.14.2

**Additional context**

**Comment by dimaMachina** [comment]
where did you find that you need to specify `parserOptions.filePath` for your graphql-config?
