### ISSUE TITLE
Report lint issues inline, not on first char of file, for Vue and Svelte

### ISSUE THREAD

**Issue by bmulholland** [dimaMachina/graphql-eslint#2103]
Is it possible to resolve the limitations that results in the workaround introduced at https://github.com/dimaMachina/graphql-eslint/pull/1346 ?

**Comment by bmulholland** [comment]
Amongst other things, I suspect this means that https://github.com/reviewdog/reviewdog (and similar, diff-based approaches) won't fail PRs that introduce linting errors, meaning we lost a critical enforcement of these policies.

**Comment by dimaMachina** [comment]
as I remember graphql-tag-pluck returns compiled code for vue/svelte files, as result - location of extracted documents will be incorrect from the source file

Maybe there is some workaround to parse vue/svelte files with vue/svelte parsers and run graphql-eslint processor on extracted js/ts code-blocks, example

```js
  overrides: [
    {
      files: ['**/*.svelte'],
      parser: 'svelte-eslint-parser',
    },
    {
      files: ['**/*.svelte/*.{js,ts}'],
      processor: '@graphql-eslint/graphql',
    }
]
```

PR welcome

**Comment by bmulholland** [comment]
Oh interesting, yeah that limitation makes sense. I suspect the strings are often the same, so also a naive string match could work to correct the locations?

I don't quite understand how the workaround with parsers would maintain location information. Why wouldn't that have the same limitation?

**Comment by bmulholland** [comment]
Just to jot down an idea I had here: pluck could add a magic comment at the top of its output, which includes the location it was extracted from. Then this could be read and added as an offset when reporting the lint.

**Comment by bmulholland** [comment]
Ran out of time today, will check this on Vue files tomorrow.

**Comment by dimaMachina** [comment]
Good, thank you!

**Comment by bmulholland** [comment]
It just works! I have a pretty complex eslint config, too. Super cool :)

I did a few checks for additional things to note, but you've covered everything in that Vue example config. Nice work!

I can update the Vue docs with the latest -- is this approach stable? If not, I'll wait to document the final state.

**Comment by dimaMachina** [comment]
Thank you for your feedback! I would be appreciated in your new docs guide update 🙏
