### ISSUE TITLE
Bug: Leading to new Errors while Upgrading package 

### ISSUE THREAD

**Issue by varshith257** [dimaMachina/graphql-eslint#2133]
**Describe the bug**

Bug: Leading to new Errors while Upgrading package typescript-eslint/eslint-plugin from 5.62.0 to 6.19.0 #8266

this is my .eslintric.json:
{
"env": {
"es2022": true,
"node": true
},
"extends": [
"eslint:recommended",
"plugin:@typescript-eslint/recommended",
"prettier"
],
"overrides": [
{
"files": ["./src/typeDefs//*.ts"],
"processor": "@graphql-eslint/graphql"
},
{
"files": ["./src/typeDefs//.graphql"],
"parser": "@graphql-eslint/eslint-plugin",
"plugins": ["@graphql-eslint"],
// Do not apply naming conventions to .graphql files
"rules": {
"@typescript-eslint/naming-convention": "off"
}
},
{
"files": ["tests/**/"],
"rules": {
"no-restricted-imports": "off"
}
},
{
// Disable explicit function return type for index.ts as it uses a lot of templated code
// which has convulated return types
"files": ["./src/index.ts", "./src/utilities/copyToClipboard.ts"],
"rules": {
"@typescript-eslint/explicit-function-return-type": "off",
"@typescript-eslint/no-empty-function": "off"
}
}
],

"parser": "@typescript-eslint/parser",
"parserOptions": {
"project": "./tsconfig.json",
"tsconfigRootDir": ".",
"ecmaVersion": "latest",
"sourceType": "module"
},

"plugins": ["https://github.com/typescript-eslint", "eslint-plugin-tsdoc", "import"],
"root": true,
"rules": {
"no-restricted-imports": [
"error",
{
"patterns": ["/src/"]
}
],

// restrict the use of same package in multiple import statements
"import/no-duplicates": "warn",

// warn/1, error/2, off/0
"tsdoc/syntax": "warn",

// Typescript Rules
"@typescript-eslint/ban-ts-comment": "warn",
"@typescript-eslint/no-explicit-any": "warn",
"@typescript-eslint/no-inferrable-types": "warn",
"@typescript-eslint/no-non-null-asserted-optional-chain": "warn",
"@typescript-eslint/no-non-null-assertion": "warn",
"@typescript-eslint/no-var-requires": "warn",
"@typescript-eslint/ban-types": "warn",
"@typescript-eslint/no-duplicate-enum-values": "warn",

// Typescript rule to enforce PascalCase naming convention for types and interfaces
"@typescript-eslint/naming-convention": [
  "error",
  // Interfaces must begin with Interface or TestInterface followed by a PascalCase name
  {
    "selector": "interface",
    "format": ["PascalCase"],
    "prefix": ["Interface", "TestInterface"]
  },
  // Type Aliases must be in PascalCase
  {
    "selector": ["typeAlias", "typeLike", "enum"],
    "format": ["PascalCase"]
  },
  {
    "selector": "typeParameter",
    "format": ["PascalCase"],
    "prefix": ["T"]
  },
  {
    "selector": "variable",
    "format": ["camelCase", "UPPER_CASE"],
    "leadingUnderscore": "allow"
  },
  {
    "selector": "parameter",
    "format": ["camelCase"],
    "leadingUnderscore": "allow"
  },
  {
    "selector": "function",
    "format": ["camelCase"]
  },
  {
    "selector": "memberLike",
    "modifiers": ["private"],
    "format": ["camelCase"],
    "leadingUnderscore": "require"
  },
  { "selector": "variable", "modifiers": ["exported"], "format": null }
],

// Typescript additional rules
"@typescript-eslint/array-type": "warn",
"@typescript-eslint/consistent-type-assertions": "warn",
"@typescript-eslint/consistent-type-imports": "warn",
"@typescript-eslint/explicit-function-return-type": "warn"
}
}
Witten override rules to use eslint/graphql-parser for .graphql files but causing this error. NEED YOUR VALUABLE GUIDANCE TO REMOVE THIS ISSUE IN MY PROJECT.
My previous version 5.6.2 worked fine with above rules but when now upgrading it leading to this new error:

**>> C:\Users\91970\Desktop\talawa\talawa-api>

talawa-api@1.0.0 lint:check
eslint . --max-warnings=1500

Oops! Something went wrong! :(

ESLint: 8.56.0

Error: Error while loading rule '@typescript-eslint/consistent-type-assertions': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
Note: detected a parser other than @typescript-eslint/parser. Make sure the parser is configured to forward "parserOptions.project" to @typescript-eslint/parser.
Occurred while linting C:\Users\91970\Desktop\talawa\talawa-api\src\typeDefs\directives.ts\0_document.graphql
at throwError (C:\Users\91970\Desktop\talawa\talawa-api\node_modules@typescript-eslint\utils\dist\eslint-utils\getParserServices.js:39:11)
at getParserServices (C:\Users\91970\Desktop\talawa\talawa-api\node_modules@typescript-eslint\utils\dist\eslint-utils\getParserServices.js:23:9)
at create (C:\Users\91970\Desktop\talawa\talawa-api\node_modules@typescript-eslint\eslint-plugin\dist\rules\consistent-type-assertions.js:90:61)
at Object.create (C:\Users\91970\Desktop\talawa\talawa-api\node_modules@typescript-eslint\utils\dist\eslint-utils\RuleCreator.js:38:20)
at createRuleListeners (C:\Users\91970\Desktop\talawa\talawa-api\node_modules\eslint\lib\linter\linter.js:895:21)
at C:\Users\91970\Desktop\talawa\talawa-api\node_modules\eslint\lib\linter\linter.js:1066:110
at Array.forEach ()
at runRules (C:\Users\91970\Desktop\talawa\talawa-api\node_modules\eslint\lib\linter\linter.js:1003:34)
at Linter._verifyWithoutProcessors (C:\Users\91970\Desktop\talawa\talawa-api\node_modules\eslint\lib\linter\linter.js:1355:31)
at Linter._verifyWithConfigArray (C:\Users\91970\Desktop\talawa\talawa-api\node_modules\eslint\lib\linter\linter.js:1807:21)**

**To Reproduce** Steps to reproduce the behavior:
npm install eslint@latest @typescript-eslint/parser@latest @typescript-eslint/eslint-plugin@latest eslint-plugin-tsdoc@latest eslint-plugin-import@latest --save-dev

npm lint:check 

**Expected behavior**

It should override the .graphql files and needs to pase with graphql/eslint-plugin as above without any errors
**Environment:**

- OS: Windows 11
- `@graphql-eslint/eslint-plugin`: 3.20.1
- Node.js: 21.1.0

**Additional context**

**Comment by dimaMachina** [comment]
https://github.com/dimaMachina/graphql-eslint/issues/544#issuecomment-891948697

**Comment by varshith257** [comment]
@dimaMachina 
Need your valuable guidance. I have tried all ways and left with no solution for it.

**Comment by varshith257** [comment]
@dimaMachina 
My .ts file has a graphql code and to lint that specific files have written override rules as shown in above. It worked fine at v5. 8.0. But recently in upgraded to v6. 19.0  but throwing error while linting
That. . ts files in typedef directory

**Comment by varshith257** [comment]
@dimaMachina  in #544   I didn't get it. 
Are you suggesting to write all parser rules even. ts outside my override rules in the override rules only. 

Hoping for  a solution for it.

**Comment by varshith257** [comment]
{
  "env": {
    "es2022": true,
    "node": true
  },
  "extends": [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "prettier"
  ],
  "overrides": [
    {
      "files": ["./src/typeDefs/**/*.ts"],
      "processor": "@graphql-eslint/graphql",
      "rules": {}
    },
    {
      "files": ["./src/typeDefs/**/*.graphql"],
      "parser": "@graphql-eslint/eslint-plugin",
      "plugins": ["@graphql-eslint"],
      "rules": {
        "@typescript-eslint/naming-convention": "off"
      }
    },
    {
      "files": ["tests/**/*"],
      "rules": {
        "no-restricted-imports": "off"
      }
    },
    {
      "files": ["./src/index.ts", "./src/utilities/copyToClipboard.ts"],
      "rules": {
        "@typescript-eslint/explicit-function-return-type": "off",
        "@typescript-eslint/no-empty-function": "off"
      }
    },
    {
      "files": ["**/*.js", "**/*.jsx"],
      "rules": {}
    }
  ],
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "project": "./tsconfig.json",
    "tsconfigRootDir": ".",
    "ecmaVersion": "latest",
    "sourceType": "module"
  },
  "plugins": ["@typescript-eslint", "eslint-plugin-tsdoc", "import"],
  "root": true,
  "rules": {
    "no-restricted-imports": [
      "error",
      {
        "patterns": ["**/src/**"]
      }
    ],
    "import/no-duplicates": "error",
    "tsdoc/syntax": "error",
    "@typescript-eslint/ban-ts-comment": "error",
    "@typescript-eslint/no-explicit-any": "error",
    "@typescript-eslint/no-inferrable-types": "error",
    "@typescript-eslint/no-non-null-asserted-optional-chain": "error",
    "@typescript-eslint/no-non-null-assertion": "error",
    "@typescript-eslint/no-var-requires": "error",
    "@typescript-eslint/ban-types": "error",
    "@typescript-eslint/no-duplicate-enum-values": "error",
    "@typescript-eslint/naming-convention": [
      "error",
      // Interfaces must begin with Interface or TestInterface followed by a PascalCase name
      {
        "selector": "interface",
        "format": ["PascalCase"],
        "prefix": ["Interface", "TestInterface"]
      },
      // Type Aliases must be in PascalCase
      {
        "selector": ["typeAlias", "typeLike", "enum"],
        "format": ["PascalCase"]
      },
      {
        "selector": "typeParameter",
        "format": ["PascalCase"],
        "prefix": ["T"]
      },
      {
        "selector": "variable",
        "format": ["camelCase", "UPPER_CASE"],
        "leadingUnderscore": "allow"
      },
      {
        "selector": "parameter",
        "format": ["camelCase"],
        "leadingUnderscore": "allow"
      },
      {
        "selector": "function",
        "format": ["camelCase"]
      },
      {
        "selector": "memberLike",
        "modifiers": ["private"],
        "format": ["camelCase"],
        "leadingUnderscore": "require"
      },
      { "selector": "variable", "modifiers": ["exported"], "format": null }
    ],
    "@typescript-eslint/array-type": "error",
    "@typescript-eslint/consistent-type-assertions": "error",
    "@typescript-eslint/consistent-type-imports": "error",
    "@typescript-eslint/explicit-function-return-type": "error"
  }
}
Done with what you suggested but same error. Help me out I am worn out to find a solution from a week to fix this issue. 


C:\Users\91970\Desktop\talawa\talawa-api>npm run lint:check

> talawa-api@1.0.0 lint:check
> eslint . --max-warnings=1500


Oops! Something went wrong! :(

ESLint: 8.56.0

Error: Error while loading rule '@typescript-eslint/consistent-type-assertions': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
Note: detected a parser other than @typescript-eslint/parser. Make sure the parser is configured to forward "parserOptions.project" to @typescript-eslint/parser.
Occurred while linting C:\Users\91970\Desktop\talawa\talawa-api\src\typeDefs\directives.ts\0_document.graphql
    at throwError (C:\Users\91970\Desktop\talawa\talawa-api\node_modules\@typescript-eslint\utils\dist\eslint-utils\getParserServices.js:39:11)
    at getParserServices (C:\Users\91970\Desktop\talawa\talawa-api\node_modules\@typescript-eslint\utils\dist\eslint-utils\getParserServices.js:23:9)
    at create (C:\Users\91970\Desktop\talawa\talawa-api\node_modules\@typescript-eslint\eslint-plugin\dist\rules\consistent-type-assertions.js:90:61)
    at Object.create (C:\Users\91970\Desktop\talawa\talawa-api\node_modules\@typescript-eslint\utils\dist\eslint-utils\RuleCreator.js:38:20)
    at createRuleListeners (C:\Users\91970\Desktop\talawa\talawa-api\node_modules\eslint\lib\linter\linter.js:895:21)
    at C:\Users\91970\Desktop\talawa\talawa-api\node_modules\eslint\lib\linter\linter.js:1066:110
    at Array.forEach (<anonymous>)
    at runRules (C:\Users\91970\Desktop\talawa\talawa-api\node_modules\eslint\lib\linter\linter.js:1003:34)
    at Linter._verifyWithoutProcessors (C:\Users\91970\Desktop\talawa\talawa-api\node_modules\eslint\lib\linter\linter.js:1355:31)
    at Linter._verifyWithConfigArray (C:\Users\91970\Desktop\talawa\talawa-api\node_modules\eslint\lib\linter\linter.js:1807:21)
(node:32300) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by dimaMachina** [comment]
@varshith257 Do you think your code comments are readable?

move below outside of top level config in own override object

```json
"env": {
"es2022": true,
"node": true
},
"extends": [
"eslint:recommended",
"plugin:@typescript-eslint/recommended",
"prettier"
],
```

**Comment by varshith257** [comment]
@dimaMachina 
Thanks for your valuable guidance on it. This issue was fixed successfully

**Comment by varshith257** [comment]
@dimaMachina 
I again went conflict for thie same error

.eslitrinc.json:
![image](https://github.com/dimaMachina/graphql-eslint/assets/117595548/501dabea-c16d-491c-998e-88b197d0eb1a)

directives.ts
![image](https://github.com/dimaMachina/graphql-eslint/assets/117595548/28d3d4d3-7cf9-4e2e-b7f8-3c633f26eb64)

Error:

![image](https://github.com/dimaMachina/graphql-eslint/assets/117595548/3f5b1e45-f91b-4f25-8689-9beac4dff588)


As above, we discussed I have moved whole to top config.
While I am upgraded to typescript-eslint parser from v5.42 to v6.19 @latest   I encountered this issue.
v5.4.2 supported this have overriden and graphql parser worken as shown in .eslintric.json for my /src/typeDefs/ .ts files but when upgraded getting above.

Hoping for a solution for this and fix it asap.

**Comment by varshith257** [comment]
@dimaMachina 
In my /src/typeDefs/ .ts files has same format of above directive.ts code Graphql+Typescript.
The overriden rules for typeDefs/.ts worked fine of @typescript-eslint-parser v5.4.2 and when upgraded to latest version v6.19.0 this issue persisted.

**Comment by varshith257** [comment]
@dimaMachina 
The same config file as in  #290 .
But different error as above

**Comment by dimaMachina** [comment]
<img width="277" alt="image" src="https://github.com/dimaMachina/graphql-eslint/assets/7361780/1b600c6b-6afb-4485-9fac-b13d41e23bef">
remove .graphql

**Comment by dimaMachina** [comment]
if you still run typescript/eslint run on graphql files your config is still invalid 
<img width="444" alt="image" src="https://github.com/dimaMachina/graphql-eslint/assets/7361780/f232083c-5497-4608-84ae-17d71e4756e7">

**Comment by varshith257** [comment]
@dimaMachina I still don't have any . graphql files in typedef directory the entire codebase is 100% is Typescript
 Wait let me share my full  config

**Comment by varshith257** [comment]
This is what they specified in the codebase of typeDef Directory: 

![image](https://github.com/dimaMachina/graphql-eslint/assets/117595548/fc2883c0-a8f5-425b-948f-922d9acf3722)

and my .eslintric.json is:

![image](https://github.com/dimaMachina/graphql-eslint/assets/117595548/e5145ce2-ce95-4c96-b93b-12ba6c608300)

![image](https://github.com/dimaMachina/graphql-eslint/assets/117595548/a10c4610-9c4d-4bfd-a374-a173bea041ff)

![image](https://github.com/dimaMachina/graphql-eslint/assets/117595548/7901811e-e851-428e-ace5-e0c1a70ac4b8)


and tsconfig.json:
![image](https://github.com/dimaMachina/graphql-eslint/assets/117595548/45fd324a-beb7-4fdd-8e61-60f7dfa5a8b1)

**Comment by varshith257** [comment]
@dimaMachina 
Hope you got the what i am intending.

**Comment by dimaMachina** [comment]
remove this from top level config and move to own override
<img width="501" alt="image" src="https://github.com/dimaMachina/graphql-eslint/assets/7361780/84a1bbfc-7a25-4590-8205-65d917f44063">

**Comment by varshith257** [comment]
@dimaMachina 
Has been done but same issue persisted:
```
{
  "env": {
    "es2022": true,
    "node": true
  },
  "extends": [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "prettier"
  ],
  "overrides": [

    {
      "files": ["./src/typeDefs/**/*.ts"],
      "processor": "@graphql-eslint/graphql"
    },
    {
      "extends":[
        "plugin:@typescript-eslint/disable-type-checked"
    ],
      "files": ["./src/typeDefs/**/*.graphql"],
      "parser": "@graphql-eslint/eslint-plugin",
      "plugins": ["@graphql-eslint"],
      // Do not apply naming conventions to .graphql files
      "rules": {
        "@typescript-eslint/naming-convention": "off"
      }
    },
    {
      "files": ["tests/**/*"],
      "rules": {
        "no-restricted-imports": "off"
      }
    },
    {
      // Disable explicit function return type for index.ts as it uses a lot of templated code
      // which has convulated return types
      "files": ["./src/index.ts", "./src/utilities/copyToClipboard.ts"],
      "rules": {
        "@typescript-eslint/explicit-function-return-type": "off",
        "@typescript-eslint/no-empty-function": "off"
      }
    }
  ],

  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "project": "./tsconfig.json",
    "tsconfigRootDir": ".",
    "ecmaVersion": "latest",
    "sourceType": "module"
  },
  "plugins": ["@typescript-eslint", "eslint-plugin-tsdoc", "import"],
  "root": true,
  "rules": {
    "no-restricted-imports": [
      "error",
      {
        "patterns": ["**/src/**"]
      }
    ],

    // restrict the use of same package in multiple import statements
    "import/no-duplicates": "error",

    // warn/1, error/2, off/0
    "tsdoc/syntax": "error",

    // Typescript Rules
    "@typescript-eslint/ban-ts-comment": "error",
    "@typescript-eslint/no-explicit-any": "error",
    "@typescript-eslint/no-inferrable-types": "error",
    "@typescript-eslint/no-non-null-asserted-optional-chain": "error",
    "@typescript-eslint/no-non-null-assertion": "error",
    "@typescript-eslint/no-var-requires": "error",
    "@typescript-eslint/ban-types": "error",
    "@typescript-eslint/no-duplicate-enum-values": "error",

    // Typescript rule to enforce PascalCase naming convention for types and interfaces
    "@typescript-eslint/naming-convention": [
      "error",
      // Interfaces must begin with Interface or TestInterface followed by a PascalCase name
      {
        "selector": "interface",
        "format": ["PascalCase"],
        "prefix": ["Interface", "TestInterface"]
      },
      // Type Aliases must be in PascalCase
      {
        "selector": ["typeAlias", "typeLike", "enum"],
        "format": ["PascalCase"]
      },
      {
        "selector": "typeParameter",
        "format": ["PascalCase"],
        "prefix": ["T"]
      },
      {
        "selector": "variable",
        "format": ["camelCase", "UPPER_CASE"],
        "leadingUnderscore": "allow"
      },
      {
        "selector": "parameter",
        "format": ["camelCase"],
        "leadingUnderscore": "allow"
      },
      {
        "selector": "function",
        "format": ["camelCase"]
      },
      {
        "selector": "memberLike",
        "modifiers": ["private"],
        "format": ["camelCase"],
        "leadingUnderscore": "require"
      },
      { "selector": "variable", "modifiers": ["exported"], "format": null }
    ],

    // Typescript additional rules
    "@typescript-eslint/array-type": "error",
    "@typescript-eslint/consistent-type-assertions": "error",
    "@typescript-eslint/consistent-type-imports": "error",
    "@typescript-eslint/explicit-function-return-type": "error"
  }
}
```

**Comment by dimaMachina** [comment]
It’s at top level and not in overrides

**Comment by varshith257** [comment]
@dimaMachina 
Same have been reproduces but no fix for this the specific error is getting when to lint .ts files graphql schema in it using override rules of processor: @graphql-eslint/graphql.
Same as specified in  documentation: https://the-guild.dev/graphql/eslint/docs/configs

When I Upgraded to latest version of typescript-eslint parser -plugin. This conflict has been started:

![WhatsApp Image 2024-01-26 at 15 49 18_0e6270ed](https://github.com/PalisadoesFoundation/talawa-api/assets/117595548/c207818b-69e9-4ca3-9326-2d233510d6a0)
