### ISSUE TITLE
Feedback for “no-unused-fields”

### ISSUE THREAD

**Issue by mashaLutskevich2002** [dimaMachina/graphql-eslint#2138]
my eslint (in the overrides)
```
{
            "files": ["**/*.graphql"],
            "parser": "@graphql-eslint/eslint-plugin",
            "parserOptions": {
                "schema": "./schema.graphql",
                "operations": "./**/*.graphql"
            },
            "plugins": ["@graphql-eslint"],
            "rules": {
                "spaced-comment": "off",
                "@graphql-eslint/no-duplicate-fields": "error",
                "@graphql-eslint/no-unused-fields": "error",
                "prettier/prettier": "off"
            }
        }
```
        
   I have a query 
```
   #import 'corgi/components/AdvTracking/AdvTrackingAdvertFragment.gql'

query ViewedProductsQuery($perPage: Int, $scroll: Float, $currentRegionId: Int) {
    viewedProducts(perPage: $perPage, scroll: $scroll) {
        products {
            product{
                ...productItemFields
                advert {
                    ...advTrackingAdvertFields

                }
            }
            timestampViewed
            timestampViewed1
        }
        hasNextPage
    }
}
```

    **`timestampViewed1` don`t use in the project, but I don`t have an error @graphql-eslint/no-unused-fields**
    
    When i run `eslint --debug src/client/components/ViewedProductsBlock/ViewedProductsQuery.graphql`
     I return 
     **Error while loading rule '@graphql-eslint/no-unused-fields': Rule `no-unused-fields` requires `parserOptions.operations` to be set and loaded**

**Comment by dimaMachina** [comment]
timestampViewed1 Is used in your query

**Comment by mashaLutskevich2002** [comment]
@dimaMachina in my query used, but I don`t use timestampViewed1 in my react project in the .tsx files. This field only in the query. Shouldn't I be getting an error because of this? Because the field is not used anywhere except for the query.

My task is "To get rid of fields that are not used in queries"

**Comment by mashaLutskevich2002** [comment]
I requested the field  timestampViewed1 in the query, but I don't use it anywhere. I should get an error because of this

**Comment by dimaMachina** [comment]
This rule warns unused fields in schema by graphql operations

**Comment by mashaLutskevich2002** [comment]
Please, tell me, is there any rule for my task?

**Comment by dimaMachina** [comment]
In graphql-eslint not

**Comment by mashaLutskevich2002** [comment]
“This rule warns unused fields in schema by graphql operations”

What does it mean? I don’t understand ((
It means that in schema is field with type. And in query (in graphql file)
this field don’t use?

нд, 21 січ. 2024 р. о 21:34 Dimitri POSTOLOV ***@***.***>
пише:

**Comment by dimaMachina** [comment]
Rule warns fields that are not selected in any graphql operations https://the-guild.dev/graphql/eslint/rules/no-unused-fields
