### ISSUE TITLE
Feedback for “no-unused-fields”

### ISSUE THREAD

**Issue by mashaLutskevich2002** [dimaMachina/graphql-eslint#2139]
What does it mean this rule? I don’t understand ((
it means that the schema has a field specified with the type. And in query (in graphql file) this field don’t use? 

For example
shema.json 
 {
            "name": "container",
            "description": null,
            "isDeprecated": false,
            "deprecationReason": null,
            "args": [],
            "type": {
              "kind": "NON_NULL",
              "name": null,
              "ofType": {
                "kind": "SCALAR",
                "name": "Boolean",
                "ofType": null
              }
            }
 },
 
 And in query (someQuery.graphql) field `container` dont`s use? Or am I misunderstanding?

**Comment by mashaLutskevich2002** [comment]
@dimaMachina This rule don`t work ((
I added to shema.json random field, in query I don`t use it. And I don`t have an error no-unused-fields

**Comment by dimaMachina** [comment]
please provide reproduction repo

**Comment by mashaLutskevich2002** [comment]
@dimaMachina This is a corporate repository and only used VPN((

Do I understand the logic of the rule correctly? Could I be wrong?

**Comment by dimaMachina** [comment]
I understand the logic of rule, I am original creator of this rule

here are docs https://the-guild.dev/graphql/eslint/rules/no-unused-fields
here are tests https://github.com/dimaMachina/graphql-eslint/blob/master/packages/plugin/__tests__/no-unused-fields.spec.ts
here are snapshots https://github.com/dimaMachina/graphql-eslint/blob/master/packages/plugin/__tests__/__snapshots__/no-unused-fields.spec.md
here is original issue https://github.com/dimaMachina/graphql-eslint/issues/9
