### ISSUE TITLE
Ability to sort nodes last in group

### ISSUE THREAD

**Issue by deathemperor** [dimaMachina/graphql-eslint#2235]
In large queries with many fields and sub fields, I prefer to put sub query nodes last. As with big queries, finding fields last under other nodes is a pain

For example:

current situation
```gql
query books {
	id
	title
	author {
		id
		addresses {
			id
			street_name
		}
		name
	}
	series {
		id
		title
	}
	created_at
	updated_at
}
```

Desire sort:

```gql
query books {
	id
	title
	created_at
	updated_at
	author {
		id
		name
		addresses {
			id
			street_name
		}
	}
	series {
		id
		title
	}
}
```

**Comment by dimaMachina** [comment]
I like this idea, pr welcome

**Comment by deathemperor** [comment]
@dimaMachina added the PR https://github.com/dimaMachina/graphql-eslint/pull/2385, I chose `relationships_last` as the config name, please suggest a better name.
