### ISSUE TITLE
error  Definition for rule '@graphql-eslint/require-selections' was not found

### ISSUE THREAD

**Issue by deathemperor** [dimaMachina/graphql-eslint#2240]
it's still [operations-recommended](https://github.com/dimaMachina/graphql-eslint/blob/master/packages/plugin/src/configs/operations-recommended.ts#L44)

**Comment by addiebarron** [comment]
In my case I had this issue because I was expecting `require-selections` to be available on the latest stable NPM version, which is `3.20.1` -- however, the documentation references version `4.0.0_alpha`. It would be nice if we could view docs for earlier versions.

**Comment by dimaMachina** [comment]
this rule was renamed in v4 from `require-id-when-available`, if you are looking for v3 docs check the link in banner

<img width="692" alt="image" src="https://github.com/user-attachments/assets/829ecb06-a51f-49d7-a5c1-8956ccda7815">
