### ISSUE TITLE
Ignore require-description for root types

### ISSUE THREAD

**Issue by ddiazghub** [dimaMachina/graphql-eslint#2259]
**Is your feature request related to a problem? Please describe**

[@nestjs/graphql](https://github.com/nestjs/graphql) does not allow to set descriptions for root types when generating a GraphQL schema with a code-first approach. This makes linting fail when descriptions are required for object types.

**Describe the solution you'd like**

The possibility to ignore this rule for root types Query, Mutation and Subscription.

**Comment by dimaMachina** [comment]
duplicate https://github.com/dimaMachina/graphql-eslint/issues/2515
