### ISSUE TITLE
linter does not pass checks

### ISSUE THREAD

**Issue by comatory** [dimaMachina/graphql-eslint#2299]
### Issue workflow progress

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [X] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox

     Run `pnpm lint`, see failing messages

- [ ] 2. A failing test has been provided
- [X] 3. A local solution has been provided
- [X] 4. A pull request is pending review

---

**Describe the bug**

Linting the whole monorepo does not pass all checks.

**To Reproduce** Steps to reproduce the behavior:

Running `pnpm lint` produces error:

```
/Users/.../Projects/graphql-eslint/website/src/components/graphql-editor.tsx
  106:20  error  Classname 'nextra-scrollbar' is not a Tailwind CSS class!  tailwindcss/no-custom-classname

/Users/.../Projects/graphql-eslint/website/src/components/play-page.tsx
  108:12  error  Classname 'nextra-scrollbar' is not a Tailwind CSS class!  tailwindcss/no-custom-classname

✖ 2 problems (2 errors, 0 warnings)
```

**Expected behavior**

All checks should pass

**Environment:**

- OS: macOS Sonoma 14.3.1
- `@graphql-eslint/eslint-plugin`: `"4.0.0-alpha.0"`
- Node.js: 18.15.0

**Additional context**

N/A

**Comment by dimaMachina** [comment]
something weird, I don't receive these errors locally, only in CI 😂
