### ISSUE TITLE
test in watch mode does not receive any input

### ISSUE THREAD

**Issue by comatory** [dimaMachina/graphql-eslint#2301]
### Issue workflow progress

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox

    > Can't easily provide failing example on Stackblitz since it is related to tooling of the monorepo itself

- [ ] 2. A failing test has been provided
- [X] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

Running `pnpm test` launches test suites in **watch** mode which is fine. The problems is, I'd like to filter down to specific unit test in the watch mode but it seems like any input I provide, it is not registered by the test runner (which I assume is `vitest`).

**To Reproduce** Steps to reproduce the behavior:

1. Run `pnpm test`
2. Wait for all the compilation to finish until "Waiting for file changes..." appears
3. Press `h` or `q` key

**Expected behavior**

I would expect menu to appear where I can enter filter mode, or even ability to quit. Only `CTRL+C` works

**Environment:**

- OS: macOS Sonoma 14.3.1
- `@graphql-eslint/eslint-plugin`: "4.0.0-alpha.0"
- Node.js: 20.11.0

**Additional context**

Check video for the behaviour, you can see the entered characters appear on screen. Maybe this is vitest issue but I've been unable to find anything similar. I use tmux so not sure if that can be an issue.

https://github.com/dimaMachina/graphql-eslint/assets/5990424/b2dd90ab-bfbd-4cb1-b226-82f518529f4b

**Comment by dimaMachina** [comment]
`pnpm test` uses `turbo` which run `npm run test` in graphql eslint monorepo

use instead

`pnpm --filter @graphql-eslint/eslint plugin test` to have possibility send inputs
