### ISSUE TITLE
Eslint 9 compatibility

### ISSUE THREAD

**Issue by lwasyl** [dimaMachina/graphql-eslint#2311]
### Issue workflow progress

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox

     > For example, you can start off by editng the
     > ['basic' example on Stackblitz](https://stackblitz.com/github/B2o5T/graphql-eslint/tree/master/examples/basic).

     > Please make sure the graphql-eslint version under `package.json` matches yours.

- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

There's an open issue to support eslint 9 flat config files: https://github.com/dimaMachina/graphql-eslint/issues/2178. However, even when opting out from flat config via `export ESLINT_USE_FLAT_CONFIG=false`, graphql-eslint fails with Eslint 9 due to:

```TypeError: Error while loading rule '@graphql-eslint/no-unreachable-types': Cannot destructure property 'schema' of 'context.parserServices' as it is undefined.```. Iiuc the problem is that several methods have been [deprecated and removed in eslint 9](https://eslint.org/blog/2023/09/preparing-custom-rules-eslint-v9/), including `context.parserServices` which graphql-eslint seems to be calling. Thus it's not only not possible to use flat config, but eslint 9 at all

**To Reproduce** Steps to reproduce the behavior:

Update eslint to version 9

**Expected behavior**

graphql-eslint still works

**Environment:**

- OS: /
- `@graphql-eslint/eslint-plugin`: 3.20.1
- Node.js: 20.13.1

**Additional context**

**Comment by ldiqual** [comment]
Workaround using the compat package from eslint:

```javascript
import { fixupPluginRules } from '@eslint/compat'
export default [
  {
    plugins: {
      '@graphql-eslint': fixupPluginRules(graphqlPlugin),
    },
    // ...
  }
]
```

**Comment by dimaMachina** [comment]
https://github.com/dimaMachina/graphql-eslint/issues/2178#issuecomment-2261600240
