### ISSUE TITLE
require-id-when-available - options not being passed through correctly

### ISSUE THREAD

**Issue by Stephen2** [dimaMachina/graphql-eslint#2410]
### Issue workflow progress

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox

     > For example, you can start off by editng the
     > ['basic' example on Stackblitz](https://stackblitz.com/github/B2o5T/graphql-eslint/tree/master/examples/basic).

     > Please make sure the graphql-eslint version under `package.json` matches yours.

- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

The rule `@graphql-eslint/require-id-when-available` doesn't seem to receive it's `options` when passed in

**To Reproduce** Steps to reproduce the behavior:

Setup a rule like:
`'@graphql-eslint/require-id-when-available': ['error', { fieldName: 'foo' }],`

The field looked for and reported on is still only `id`.

I got more logging by editing the minified dist file `cjs/rules/require-id-when-available.js`:
```
    const { fieldName = DEFAULT_ID_FIELD_NAME } = context.options[0] || {};


    console.log("options", {
      o: context.options,
      c: JSON.stringify(context),
    })
```

Which produces:
```
options {
  o: [],
  c: '{"id":"@graphql-eslint/require-id-when-available","options":[]}'
}
```

Options aren't passed through, so I can't specify alternative names than `id` to look for

**Expected behavior**

I can pass options through to the rule.

**Environment:**

- OS: MacOS
- `@graphql-eslint/eslint-plugin`: @graphql-eslint/eslint-plugin@3.20.1
- Node.js: v18.20.3, npm: 10.7.0

**Additional context**

**Comment by dimaMachina** [comment]
Are you still having this problem? since nobody else reported I guess problem was on your side, closing for now, feel free to reply and I'll reopen if you still need help
