### ISSUE TITLE
`json-schema-to-ts` belongs in `dependencies`

### ISSUE THREAD

**Issue by alecmev** [dimaMachina/graphql-eslint#2441]
### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

When type-checking a project with `@graphql-eslint/eslint-plugin` and `skipLibCheck: false`, I get the following:

```
node_modules/@graphql-eslint/eslint-plugin/esm/types.d.mts:4:28 - error TS2307: Cannot find module 'json-schema-to-ts' or its corresponding type declarations.
│ 
│ 4 import { JSONSchema } from 'json-schema-to-ts';
```

**To reproduce**

Just `skipLibCheck: false` is enough.

**Expected behavior**

No errors.

**Environment:**

- `@graphql-eslint/eslint-plugin`: `4.0.0-alpha.0`

**Additional context**

Workaround with Yarn:

```yaml
packageExtensions:
  '@graphql-eslint/eslint-plugin@*':
    dependencies:
      json-schema-to-ts: ^2
```

Let me know if you need more details or a reproduction.

**Comment by dimaMachina** [comment]
Hi! I don't think I want to include types dependency in `package.json`'s `dependencies`, wdyt @dotansimha ?

**Comment by alecmev** [comment]
At least as an optional peer dependency? [Similar discussion in ESLint](https://github.com/eslint/rewrite/issues/104).

**Comment by dimaMachina** [comment]
LGTM Feel free submit a PR
