### ISSUE TITLE
Add option to `@graphql-eslint/require-description` to ignore types with specific patterns in their names

### ISSUE THREAD

**Issue by benediktms** [dimaMachina/graphql-eslint#2515]
**Is your feature request related to a problem? Please describe.**

When writing queries with [pagination](https://graphql.org/learn/pagination/#complete-connection-model) types often use `Connection` and `Edge` in their names. Adding descriptions to the schema is good, but for types like these it doesn't make sense/add much value.

**Describe the solution you'd like**

It would be great if `@graphql-eslint/require-description` could accept a regex or something for type names that should be ignored by the rule.

**Describe alternatives you've considered**

Ignoring the lint warnings, but this adds noise to the lint output. It also means the rule could never be switched from 'warn' to 'error' without adding these redundant descriptions.

**Comment by dimaMachina** [comment]
Looks good to me, do you want to submit a pr? take a look of new option in `no-unused-fields` https://github.com/dimaMachina/graphql-eslint/blob/c53cb4e8e462f65e880cb700020602081632503c/packages/plugin/src/rules/no-unused-fields/index.ts#L221

should be helpful
