### ISSUE TITLE
Support graphql-java schema lint

### ISSUE THREAD

**Issue by chenrui333** [dimaMachina/graphql-eslint#2522]
**Is your feature request related to a problem? Please describe.**

I hava a graphql-js implementation calling graphql-java, while I was trying to deprecate some field in a fragment, I ran into the validation error, I wonder if there is a way to catch that with this tool.

https://www.graphql-java.com/documentation/sdl-directives#declaring-directives

**Describe the solution you'd like**

Support linting for `deprecated` directive locations

**Describe alternatives you've considered**

n/a

**Additional context**

Error message

```
Validation error (MisplacedDirective@[xx/xx]) : Directive \'deprecated\' not allowed here\n\nPath: xx/xx/xx."	
```

-------

I can see this is a problem btw the different graphql implementations.

<img width="847" alt="image" src="https://github.com/user-attachments/assets/aef501a3-b08a-421c-9bd7-6d8410d03591">

relates to https://github.com/graphql-java/graphql-java/issues/3694

**Comment by dimaMachina** [comment]
please provide example of code which you want to lint, closing for now due time, feel free to reply and I'll reopen
