### ISSUE TITLE
Cannot read properties of undefined (reading 'parserServices')

### ISSUE THREAD

**Issue by waynezhang1995** [dimaMachina/graphql-eslint#2569]
### Issue workflow progress

We are on `@graphql-eslint/eslint-plugin@4.0.0-alpha.0`. 

This is our `eslintrc`
```javascript
 files: ['*.graphql'],
 parser: '@graphql-eslint/eslint-plugin',
 plugins: ['@graphql-eslint'],
 rules: {
       ....
```

`.graphqlrc.yml`
```javascript
schema:
    - internal/graph/schema/**/*.graphql
    - scripts/**/*.graphql
```

the above error is coming from
```javascript 
function requireGraphQLSchemaFromContext(ruleId, context) {
  const { schema } = context.sourceCode.parserServices;
  if (!schema)
    throw new Error(
      `Rule \`${ruleId}\` requires graphql-config \`schema\` field to be set and loaded. See https://the-guild.dev/graphql/config/docs/user/schema for more info`
    );
  return schema;
}
```

and interestingly, if we change `context.sourceCode` to `context.getSourceCode()` everything starts working normally.

Appreciate any helps. Thanks

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox

     > For example, you can start off by editng the
     > ['basic' example on Stackblitz](https://stackblitz.com/github/B2o5T/graphql-eslint/tree/master/examples/basic).

     > Please make sure the graphql-eslint version under `package.json` matches yours.

- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

**To Reproduce** Steps to reproduce the behavior:

**Expected behavior**

**Environment:**

- OS:
- `@graphql-eslint/eslint-plugin`:
- Node.js:

**Additional context**

**Comment by alecmev** [comment]
Similar issue for us, but with `documents`. `getSourceCode()` doesn't seem to help either. Sprinkled some `console.log`s, and looks like the wrong `graphql.config.*` is being loaded/used. It's a monorepo and we have more than one, and one of them doesn't have `documents`, because there aren't any in that particular package, only schemas.

**Comment by dimaMachina** [comment]
GraphQL ESLint[ requires ESLint minimum v8.44.0](https://github.com/dimaMachina/graphql-eslint/blob/88a6391d3fa0340f4756646becdc23bd8d5e4d08/packages/plugin/package.json#L38) according his `peerDependencies` since

https://eslint.org/blog/2023/06/eslint-v8.44.0-released/

> [!note]
>
> The `context.parserServices` property is now deprecated in favor of [SourceCode#parserServices](https://eslint.org/docs/latest/extend/custom-rules#accessing-the-source-code). This change is part of the [implementation of language plugins](https://github.com/eslint/eslint/issues/16999).
