### ISSUE TITLE
Unable to lint federation v2 schemas in v4 graphql-eslint

### ISSUE THREAD

**Issue by InsidersByte** [dimaMachina/graphql-eslint#2812]
### Issue workflow progress

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox

     > For example, you can start off by editing the
     > ['basic' example on Stackblitz](https://stackblitz.com/github/dimaMachina/graphql-eslint/tree/master/examples/graphql-config).

     > Please make sure the graphql-eslint version under `package.json` matches yours.

- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

When attempting to lint a federation v2 schema with `v4` of graphql-eslint that includes a federation directive e.g. `@key`. It fails with the error below.

```
Parsing error: Error while loading schema: Unknown directive "@key".

Unknown directive "@link".
```

It was possible to lint with `v3` of graphql-eslint by setting `parserOptions.schemaOptions.assumeValid` to true, but it doesn't seem possible to do this in `v4`.

**To Reproduce** Steps to reproduce the behavior:

You can see an example failing schema [here on the playground](https://the-guild.dev/graphql/eslint/play?s=scalar+DateTime%0A%0Atype+Post+%40key%28fields%3A+%22id%22%29+%7B%0A++id%3A+ID%21%0A++title%3A+String%0A++createdAt%3A+DateTime%0A++modifiedAt%3A+DateTime%0A%7D%0A%0Atype+Query+%7B%0A++post%3A+Post%21%0A++posts%3A+%5BPost%21%5D%0A%7D%0A%0Aextend+schema%0A++%40link%28%0A++++url%3A+%22https%3A%2F%2Fspecs.apollo.dev%2Ffederation%2Fv2.3%22%2C%0A++++import%3A+%5B%22%40key%22%5D%0A++%29 ).

**Expected behavior**

To be able to lint federation v2 schemas.

**Environment:**

- `@graphql-eslint/eslint-plugin`: 4.2.1

**Additional context**

I did see both of the following and while they are related it might not be the only way to resolve this issue hence I raised another one. Feel free to close if you think its appropriate:
* https://github.com/dimaMachina/graphql-eslint/issues/1824 
* https://github.com/dimaMachina/graphql-eslint/pull/2049

**Comment by dimaMachina** [comment]
try `4.3.0-alpha-20241204113935-074a093b359d2947f263679eac8596958876a3b6`

`graphql-eslint` should parse federation subgraphs without parse errors and you could even use [`known-directives` rule](https://the-guild.dev/graphql/eslint/rules/known-directives) which previously reported errors about unknown `@link` directive.

But for linting federation subgraphs schemas optional peer dependency `@apollo/subgraph` should be installed (you'll get runtime error in case of missing it)

**Comment by InsidersByte** [comment]
I just tried it and it worked great! 

Thanks
